"""baseline — schema is created by SQLModel.create_all on first boot, then
stamped to this revision. Future model changes get real autogenerated
migrations from here. This keeps v4a's one-time reset simple while making
Alembic authoritative going forward (no more down -v).

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-12
"""
from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # No-op: create_all builds the baseline; we stamp to here.
    pass


def downgrade() -> None:
    pass
